language: php

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
#    - cubrid/9.3.0
    - vendor
    - $HOME/.composer/cache

php:
  # - 5.3
  - 5.4
  - 5.5
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8


install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 7.
  - travis_retry composer self-update && composer --version
  - composer global require drush/drush:6.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Build Codebase.
  - TESTDIR=$(pwd)
  - cd ..
  - git clone --branch 7.x --depth 1 http://git.drupal.org/project/drupal.git drupal
  - cd drupal

  # Disable sendmail (PHP)
  - if [[ "$TRAVIS_PHP_VERSION" = "php*" ]]; then echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  # Disable sendmail (HHVM)
  - if [[ "$TRAVIS_PHP_VERSION" = "hhv*" ]]; then echo sendmail_path=`which true` >> /etc/hhvm/php.ini; fi

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:
  - ln -s $TESTDIR modules/commerce_discount

  # Update drupal core
  - drush si --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce" --yes
  - drush dl addressfield rules ctools entity views
  #- drush dl commerce commerce_customer_ui commerce_product_ui commerce_line_item_ui commerce_order_ui
  #- drush dl commerce_payment commerce_payment_example commerce_tax_ui
  #- drush dl commerce_checkout
  - drush en -y simpletest
  - drush en -y commerce_discount commerce_discount_date commerce_discount_usage

  # Start server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done

script:
  # Run the tests
  - drush test-run --uri=http://127.0.0.1:8888 "Commerce discounts"
